name: NuGet Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build and test
      run: dotnet build --configuration Release --no-restore

    - name: Publish NuGet package
      run: |
        dotnet pack --configuration Release --no-build --no-restore --include-symbols
        dotnet nuget push --skip-duplicate ./Rebar.Core/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
